:

In [3]:
import os
import json
import pandas as pd
from dotenv import load_dotenv

#load .env
load_dotenv()

with open("config/config.json","r") as f:
    config = json.load(f)

print(config)

{'llm': {'openai_model': 'gpt-4o-mini', 'gemini_model': 'gemini-1.5-flash', 'temperature': 0.3}, 'evaluation': {'criteria': ['tone_empathy', 'knowledge_accuracy', 'resolution_quality'], 'score_range': [1, 5]}, 'classification': {'labels': ['billing', 'claims', 'complaint', 'general_query']}}

In [4]:
df = pd.read_csv("data/transcripts.csv")

print("Data Loaded")
print(df.head())

Data Loaded
   call_id agent_name                                         transcript  \
0        1      Alice  Customer: I was charged twice for my premium t...
1        2        Bob  Customer: My claim has been pending for 2 week...
2        3    Charlie  Customer: This is the third time I'm calling! ...
3        4      Diana  Customer: Can you explain my coverage details?...

  expected_call_type
0            billing
1             claims
2          complaint
3      general_query

In [5]:
df.tail(2)

,call_id,agent_name,transcript,expected_call_type
2,3,Charlie,Customer: This is the third time I'm calling! ...,complaint
3,4,Diana,Customer: Can you explain my coverage details?...,general_query

In [6]:
df.head()

,call_id,agent_name,transcript,expected_call_type
0,1,Alice,Customer: I was charged twice for my premium t...,billing
1,2,Bob,Customer: My claim has been pending for 2 week...,claims
2,3,Charlie,Customer: This is the third time I'm calling! ...,complaint
3,4,Diana,Customer: Can you explain my coverage details?...,general_query